<%
/*
 * Copyright (c) 2011-2017 LabKey Corporation
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
%>
<%@ page import="org.labkey.flow.FlowModule" %>
<%@ page import="org.labkey.flow.analysis.model.IWorkspace" %>
<%@ page import="org.labkey.flow.analysis.model.PCWorkspace" %>
<%@ page import="org.labkey.flow.controllers.WorkspaceData" %>
<%@ page import="org.labkey.flow.controllers.executescript.AnalysisEngine" %>
<%@ page import="org.labkey.flow.controllers.executescript.ImportAnalysisForm" %>
<%@ page extends="org.labkey.api.jsp.JspBase" %>
<%
    ImportAnalysisForm form = (ImportAnalysisForm)getModelBean();

    WorkspaceData workspaceData = form.getWorkspace();
    IWorkspace workspace = workspaceData.getWorkspaceObject();
    String workspaceName = workspaceData.getPath() != null ? workspaceData.getPath() : workspaceData.getName();
    assert !(workspace instanceof PCWorkspace) : "R Engine can only be used on Mac FlowJo workspaces";
%>

<input type="hidden" name="selectFCSFilesOption" id="selectFCSFilesOption" value="<%=h(form.getSelectFCSFilesOption())%>">
<input type="hidden" name="existingKeywordRunId" id="existingKeywordRunId" value="<%=h(form.getExistingKeywordRunId())%>">
<% if (form.getKeywordDir() != null) for (String keywordDir : form.getKeywordDir()) { %>
<input type="hidden" name="keywordDir" value="<%=h(keywordDir)%>">
<% } %>
<input type="hidden" name="resolving" value="<%=form.isResolving()%>">

<p>Select analysis engine for <%=h(workspace.getKindName())%> <em>'<%=h(workspaceName)%>'</em>.
</p>
<hr/>
<input type="radio" name="selectAnalysisEngine" id="<%=AnalysisEngine.FlowJoWorkspace%>" value="<%=AnalysisEngine.FlowJoWorkspace%>"<%=checked(AnalysisEngine.FlowJoWorkspace == form.getSelectAnalysisEngine())%> />
FlowJo statistics with <%=h(FlowModule.getLongProductName())%> graphs.
<div style="padding-left: 2em; padding-bottom: 1em;">
    Statistics from the <%=h(workspace.getKindName())%> are imported and
    graphs will be generated by <%=h(FlowModule.getLongProductName())%>.
</div>

<input type="radio" name="selectAnalysisEngine" id="<%=AnalysisEngine.R%>" value="<%=AnalysisEngine.R%>"<%=checked(AnalysisEngine.R == form.getSelectAnalysisEngine())%> />
R statistics and graphs.
<div style="padding-left: 2em; padding-bottom: 1em;">
    The analysis defined in the <%=h(workspace.getKindName())%> will be used
    by the R engine to generate statistics and graphs.<br>
    R must be configured and the flowWorkspace library must be installed to use this engine.
</div>


